"""
Copy template choosen from TEMPLATES to main folder.

Copy content from env template (autogenerated passwords etc) 
to .env which is gitignored, then remove template env file as it is redundant.
"""
from pathlib import Path
from shutil import copytree, rmtree

PROJECT_NAME = "{{ cookiecutter.project_name }}"
USE_FASTAPI_USERS = bool("{{ cookiecutter.use_fastapi_users }}")
TEMPLATES = ["template_fastapi_users", "template_minimal"]


def copy_choosen_template_to_main_dir(used_template: str):
    if used_template not in TEMPLATES:
        raise ValueError(f"{used_template} not in {TEMPLATES}")

    copytree(used_template, "./", dirs_exist_ok=True)

    for template in TEMPLATES:
        rmtree(Path(template))


def create_env_file_and_remove_env_template():
    env_template_file = Path(".env.template")
    env_file = Path(".env")

    env_file.write_text(env_template_file.read_text())
    env_template_file.unlink()


if __name__ == "__main__":
    if USE_FASTAPI_USERS:
        used_template = "template_fastapi_users"
    else:
        used_template = "template_minimal"

    copy_choosen_template_to_main_dir(used_template=used_template)
    create_env_file_and_remove_env_template()
