"""
Copy content from env template (autogenerated passwords etc)
to .env which is gitignored, then remove template env file as it is redundant.
"""
from pathlib import Path

PROJECT_NAME = "{{ cookiecutter.project_name }}"


def create_env_file_and_remove_env_template():
    env_template_file = Path(".env.template")
    env_file = Path(".env")

    env_file.write_text(env_template_file.read_text())
    env_template_file.unlink()


if __name__ == "__main__":
    create_env_file_and_remove_env_template()
